version: "3"

services:
  app:
    build: .
    environment:
      - DATABASE_URL=mysql+pymysql://zua:password@host:port/todoAPP
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todoAPP
      - MYSQL_USER=zua
      - MYSQL_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
