version: '3.8'
services:

  db:
    image: mysql:8.0
    container_name: mysql_container
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=todoAPP
      - MYSQL_USER=zua
      - MYSQL_PASSWORD=password
      - MYSQL_MAX_CONNECTIONS=10
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    restart: always
    container_name: api_container
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://zua:password@db/todoAPP"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: /entrypoint.sh
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000


    
volumes:
  db:
    driver: local

